---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: agent-dvr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ispy-agent-dvr
      version: 2.0.61
      sourceRef:
        kind: HelmRepository
        name: true-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: doitandbedone/ispyagentdvr
      tag: 4.1.3.0
      pullPolicy: IfNotPresent
    persistence:
      config:
        storageClass: nfs-client
      media:
        storageClass: nfs-client
      commands:
        storageClass: nfs-client
    ingress:
      main:
        enabled: true
        entrypoint: web
        # annotations:
        #   traefik.ingress.kubernetes.io/router.entrypoints: "web"
        autoLink: true
        enableFixedMiddlewares: false
        hosts:
          - host: "dvr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
