---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: game-servers
spec:
  interval: 5m
  chart:
    spec:
      chart: satisfactory
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: true

      server-cache:
        enabled: true
