data:
    k8s:
        user_password: ENC[AES256_GCM,data:Rp/fO71+,iv:F5OATTAHLhGH170aVkvr7fWvb5fO+0h3KSXabUZ0kSQ=,tag:b0fRcYkrhnhD2JCCYPjaWQ==,type:str]
        ssh_key: ENC[AES256_GCM,data:cntDFH3qrR3i9nU3GULLCfgSsWZ5r5StEKfa6tjF6AxvHO5AHoUQIy7105cEQHUT0J3vGElJAQkM02L4H3rJFGUB3aFiR7/yfpFidmt46/3abcxcntHMODMSZf4=,iv:XFDcuP0bUFlIs3zaYx8nKGsSir1P/+a75TRf+9q3cm8=,tag:Sv0xdEYZFI6HJnmxlxp0bQ==,type:str]
    pm:
        api_token: ENC[AES256_GCM,data:O1lhMJs=,iv:z0d2smN4eBYOYFAqhfCZNDbGceux5MT3P1jyxgrCS/8=,tag:erWZAUJzAXZEZrjhqOtLeA==,type:str]
        api_token_secret: ENC[AES256_GCM,data:z29+SvLSbGPnsPnNNEbyeNqYPxeVV2dSdOYVgxGoO2VxvQS+,iv:HI4EgbZzSSJv3i8WavH8Tz+LbEiWKtanwfSLgpAXH/A=,tag:y7BKOhNOybbzb5VwMQCytQ==,type:str]
        user: ENC[AES256_GCM,data:lpnZrJTXp9E=,iv:dbiF/v6AZ1iS0blxxzzheUj2Vx8S/1IEwN10/efOEqc=,tag:kI//wx9ZzzobvkruHZ3MkA==,type:str]
        password: ENC[AES256_GCM,data:1140W6X5xCA=,iv:REJSkKSEjgG3dmgKUqNZnpOm17vR+E8wC/5JJavtA70=,tag:C4mkWmOh1LUZmkW1elfjTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR1pYUXl6aDZoalAyeU45
            YStGcnk5QXlEOTRudmJTQlJuRWRrZmd3OVI0CklLZnlvSkJkQnJhamgxZUd4S0tT
            SnpDcnNpSzl0cTAyaDVleUMrenc4WkUKLS0tIFNCaWxpaDFYdVJCcURJb2FqWG0v
            SGI0UVZwRkw3c0IyWHNkSmlSQzRUcTQKPUlaCrtMMSL7vT3MBLDgzSg0VGss33Ek
            ig5Hk0ecjpEThtX63oqx4niA5OK6yqk7Poweckwe10kZLZMG8hXp6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T22:12:22Z"
    mac: ENC[AES256_GCM,data:rwNUU8W3qhKind/lBRVZKAdegxJ+NsjrrMdRWq1nBQhrwHAnDIP8gjte7CLltR+Bnlqw+kGtaPE32aJ/QdyiIhbcvRrDtIVklxXqXC9nxfNDQZetPuwM383ydPmAi892QhS4QrlELkfW+Vs0OpduT829nCcW14vM1vifteTuVoQ=,iv:bImwn2vaNqsauQUFcCXwzAyrm+jKpj3+e+Isjoh0qx4=,tag:w1mACQYzJGRf2y5WUhucxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
