apiVersion: v1
kind: Secret
metadata:
    name: matterbridge-toml
    namespace: default
type: Opaque
data:
    matterbridge.toml: ENC[AES256_GCM,data:D0X3HkKUkMApoOmUrA2VbhfZyN/9Bx7ljfv0+6RJt6Tt3KEDd/F2RE3NOPerBbY9c8UDyFoB2/xhXwMsbfrDDjy+RWXFugRxo9SCTF88NieC1hS4ljU8RoFXZ/qFvkAIptjRoIocymy9pII6QM2CPHDpcaBxAXFWEBQsE4SIgKrSp9JsOzbR5sBWAkElfbUn1Cf9xft6kFbQjTLy5Ki4lKzIwLBBwMVdG7eBfJM5H1WR/ksmFcS7LW5EMVAf9A3R1r0gOGInm7ustecZMIcM8l1aHRLTxmGj2m6NaKdRrTqcw9RnVzCY77QUDOVfsMY5S/DOCZXe6Jf/K6BY7I6+bAA/GNawRRLTDbEklNlDlly/5DL8ObtaZXHLRG7H7iCpYCOl2KfvEEElMlhBCiDOWxeCDY7UF+LNwgWA290RHR11Mqt5qJGQZ61udG4kHxgqMuaPob0MJGRaptWotf0QqbxQSvUhHtO+twNt11or1AgEuwWHfqKdEqV5SsnEz8JjCZGu6Nvo57cP9aUMvMqtgc2rmXg0rEv/ebMjCrmy0nCeT2gxvulx+za61XK7svQ+tTwVNRYIjOepqffGp540RNgsWAKmQnI8we4teEIdslYwx5STAmdVzuoOoeoGcR6qS3EavT60GYl3ecjq+PlFIOnSLqFa4At2MOwB2V+FRGzw0oPD5DDxRwO0C2GL2sGFlvtRroQbpldZbXftiCnevaDv5tobvDIXhc7gKZhrAvhW+S5ExHr/hMr7dqeIiMwWKWRs66tBdj6zGgqoPshX+Budhr6BNGIEkGzqklgjfnzmUd/jXwR3hLCbrhV35y12y1S0n3U3Af6RfKoptV1+/zvn6W9ew4zl0aTRqrqOcIO1+v7bVzNWh/phIBrgC2XdlRMvrOYuWmlOkW20g6ygs+QpwI04RFk4Jyc9SHc6av5PcjaWtf6CsOP/GyOLU1DaRTWIDKC56lMcQ90UbysaQLjurWczm6PaOO52waQq2T9un0qSSN8kYeD6/4EAEX6CNVknqwslBkTznBPYiTXumkXdAForaW0R3+y8ehrivsNslTi3/h7gEYP8MeznM7AcXApksV7z1mWk0pwrk9Mkj6NTyymSvAF0ERrI/PUoMPRR7ctZwY93XkDZJA3sfv4coZIGcTYtjHk6y61pzYkZLK+nj/ExbMWelYBAsGEqqiHWG7BnibbsS2IIFHopqtDkST6W2xuWivwM+fIilsuhvxjx5nQ3oxsa0KHc8mC8WJmiR+rmRpWF/UHDQuKJz8Nc1d8XTb40de/rGw+j47toBiaoQRcZzpfjxlYd896eIlWqz21jrCQlmvF+s6DFix7t8nNQpkbaIcvTsyg/cJoH3Nyn7771q1KdAdj4FA49ASu+EK+vbFNIu2deHPH7jLFhgTI7v0DS78JtektS32ZctdMp3pwa0HzDqzlt987jJQlYTQ1/I/DyjC2Qy0bHuTMeIgvQDvU8j7Rp9DIETk0N2CzbLLRfcBSL,iv:a4IZY1Kw6KZKiOYbjDmq025DbPf/Cwj4mXokatw7XNU=,tag:ilnZ5R0nXwubasqAHDclQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGpiUllpdjg0Y2NlZFpF
            L1QwQkxxODc4Vmh5cjBnNlJHcDVoV0pTSFMwCjI0a2FMQVFNU2ZNVlNzSHBVd0F0
            czUwS1ZPL1AreFNUQzNqR0Fsc0NwbkUKLS0tIHVlVXROdzAzQnV0azc4N0RQOTJw
            OEttQWI4TEpubFBlK2Z5VmJUSHN1SWMKl4oF3Ao8TdKXhX8l/hzSzWY699sZmotl
            tShWTuUdtR5eEUMUZXQv3maVTVn1YTrx8JAIboOiR7KcIhYbmQ3Ahw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:33:02Z"
    mac: ENC[AES256_GCM,data:g9c/P3zoCKrFMxiHlplS57kj2CRwBdR4lkBT8jGxuinpot0+7QrVvIVk5CJST1OLiY8rbcdLT9U3Dg7gXNUen0kAOieOvEkMt8AyUUklwCcZaH+9QBEN3P1hZn0/liVKZ+x3ZCtaCjMFYvbF18s2BFv83KxSq/UePDkhHyrHuSE=,iv:etUC+z+4We14zigHHPPIhdDRk/Ucyb/+OsJqzrhfso4=,tag:Qo4jcAOpcw48OSYy5vsm/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
