apiVersion: v1
kind: Secret
metadata:
    name: matterbridge-toml
    namespace: default
type: Opaque
data:
    matterbridge.toml: ENC[AES256_GCM,data:kHY/GUAPXrCPGle9+E8jIxSQAC3WcDoUWyx4MojsnwoqgBmgtkyJvzHkhRANV+ItgJ8gxXXU1efCuMfqCrbbiFCZWFPGp/LXnLfMrZSZ4gETNX6YH7vzNLqt64cy8WmvQ8sBBeaGIOfb91iGV5ZLs2vIXy652EosIjcpP76uyM6eyoz+zv8CbU7haHSxfg5GbTycDJz1akA2gWQZBuAbsWHECWerlZm7iydkC4d7zUfJf1Eas/T6uwjCsNCkIiElL3S6vsRsjiH9c2B2KXXQpB/ekIdnf0JA7QliZXu1xYR0mxPFptG/SlJOLKo4ggCeWn0q2U7FzhVphtIWtADUlsJDWe05vyIy7B0bzPWW3LIaRVv7DUFu84TCFFG8farrDvd6eNTY77fkP926Z/AjYueFQ01yLJy+/02KAS5/vznI1MTSOim99INxsN40WFiPg5e/suVsBbx7WUFGtF7Gsf9KGAfsMoRweOD12Q3GJTTBUI8ZinXxN5ka5ZmB22JxI1T3Rbpqd/tdr0iZPqbAfFtzWQ9NdDZeR9I3HDrYmNEz0BU3gOS9UadqywOGKGk7v///jgGUyqEvzCC/piPXiIkF0sPtyQr8t3gMJ2928tjddvoQ3e2z/eLTnYmBTA8IRrJ90rAYN2B5CXlvGqrO3OG7qBqpbBrM5KqHRibLnnN2xV0+9xds9L9EdAieoCJVfkWDYFbbHKn8ydX82iQzhtHpksbrvUmWlaJx8jRckCJWNr7QpVij0PhP/aqxfnCxiAcp1T5JRNGdeVIFpFFl33Kfck/815ZPDYgwT3wbcMrY6ijyGDmOoVgeb+Y6sq0usnDF5eJfD9fZdUcq4mZuHv1e42cm+zIs6UQuNkgc6a7Df88T6bw4NG+dAE/uKAxsGc9f+0gnPqC9uKeakFvJ1xPyaNEp+vLb23JkyHu56ZLReZ0WwGKRxeSAo1uwlobcLefl7macKbZ2purW47h7cXdkAfXGG6b4OQwcTt+wCx3dF3ExuaNbS3dnJIdb9VM3Npa1VTE/qeOLMgsj7zigFHFzxSCE1J8bNNMC+mK51MrptOpefQK5cuZjDXhI/pwYulKJYal9QuNNxk3QXhbJEOY/6+tb+4fa+xrG+bwi5UMBV0PpRCuPdpzXRryIWCstKqwAXhhQE6OcgIQbNTzZNzfVf/Jw5RSdMmT+/eugA6FzB7ymrtXuF42mh2cNmdEN5hs4+4Ag9SNmFm8/O2cb1ywQQg1W6Gm1xXYgK2IRARuv9olaZyEHkstSz8wJ8y2JIyH7pZ82ZGs9dRhiQ2J7VLsbDr9LQT4OfCBWCrupwU3k+2rpFbEMSvV8qFkj2TG6W0YC+hGaA/BzxozpdDF5d+YN1XAQvDBBrktjXVgi+J2YDLxDxCgZRJKJ/GwWbbmgZqNLuA==,iv:FCZvrn3MP0bA3GfyQI28p/sre1JTHRJV0UDV1oVt6iM=,tag:XSkXEoRIZJTQDKvve4Q14w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGpiUllpdjg0Y2NlZFpF
            L1QwQkxxODc4Vmh5cjBnNlJHcDVoV0pTSFMwCjI0a2FMQVFNU2ZNVlNzSHBVd0F0
            czUwS1ZPL1AreFNUQzNqR0Fsc0NwbkUKLS0tIHVlVXROdzAzQnV0azc4N0RQOTJw
            OEttQWI4TEpubFBlK2Z5VmJUSHN1SWMKl4oF3Ao8TdKXhX8l/hzSzWY699sZmotl
            tShWTuUdtR5eEUMUZXQv3maVTVn1YTrx8JAIboOiR7KcIhYbmQ3Ahw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:51:11Z"
    mac: ENC[AES256_GCM,data:+4B28sVsP+y96GYt+IYLiP4DwDPCQ3wddXgr+dG372NqfHXmY9Gg/gQVL9asNW++qws9HjFvM3SmnWF6G+DhRe5ZNbViuU6wYgf6VKvswI6PyiWT/caJEsFCdWBpsZmr1X9aM0UmLKsHEohRg5jga6dQAc8ZD1GsGdANTaZZwxE=,iv:9xdNvo4W9zVfFLqLmi79+c/+KVMYUzbtUmvVRyGa4aA=,tag:KyMpnYuXvZk9UGZ3uiTa3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
