apiVersion: v1
kind: Secret
metadata:
    name: matterbridge-secrets
    namespace: default
type: Opaque
data:
    MATTERBRIDGE_DISCORD_OI_TOKEN: ENC[AES256_GCM,data:xkKuXETbawqAEsLpIE0O6cKLQXNlKgm9mhcFXMThO1+fpvwr23vjYPWWMyE2X7eCJYTpklVdAoYootGn+V2GnzEKnTM2vMkoa9o+AuLXxUg=,iv:LykM2MmkseKi1KFNjH2X8LLRMxB0NjQGM/Vx+KbJo1s=,tag:OClp0M3u6sEUWnczdGSRfg==,type:str]
    MATTERBRIDGE_IRC_ALPHACHAT_NICKSERVPASSWORD: ENC[AES256_GCM,data:PKbXMFdavj9lN7cZLKW5k+Jnh3v0bG2iRZF+PkT3TXLFfu9QXeY+nsHHKYQ=,iv:lMKJA+HsMQNCM1tst7QB/AvbN5GUvau6/ROSD/eic3o=,tag:nlcfIcTMdfFJG4MOyMCNeg==,type:str]
    MATTERBRIDGE_IRC_ALPHACHAT_PASSWORD: ENC[AES256_GCM,data:Yg9LrHs2uTTCA4QXQd2Ox41WW2lmXBC0MuwNguE6bSuAIuaQ+Hp1T0iERV7XQIxEsApimda9/RRHu+1fiWDnBB0deH0GDIl5EvI4cWjNNGtSHswU,iv:/6X7JksLNJKmxFfSfz9rJ2IqOcJwDlVyBYFNr25DAWs=,tag:Pa1I6jFEkmtC3v3ptjYYPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGpiUllpdjg0Y2NlZFpF
            L1QwQkxxODc4Vmh5cjBnNlJHcDVoV0pTSFMwCjI0a2FMQVFNU2ZNVlNzSHBVd0F0
            czUwS1ZPL1AreFNUQzNqR0Fsc0NwbkUKLS0tIHVlVXROdzAzQnV0azc4N0RQOTJw
            OEttQWI4TEpubFBlK2Z5VmJUSHN1SWMKl4oF3Ao8TdKXhX8l/hzSzWY699sZmotl
            tShWTuUdtR5eEUMUZXQv3maVTVn1YTrx8JAIboOiR7KcIhYbmQ3Ahw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T16:31:06Z"
    mac: ENC[AES256_GCM,data:grPI9ptEynzk4NMP9TczSEs+k8/XSa2KEssBjFCFMk52g5i9uZwEENZqwC09L/Undrm472ahnML4KzDHQIhnAafKmmBz+2XU5ppjsXVotC2Vr9Pv1KBJYtrw5bhN1whSm6YGxVF/1D1P1UpFofqzmLCJ9TlSCMgTMSglfjMiZ84=,iv:HcnZrILLXQMyiNtwQhbGRxyP0y2gXmqX8qMfu8/0Yhc=,tag:dE/3DecVnF1YRGVkoGcu3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
