---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matterbridge-toml
  namespace: default
data:
  matterbridge.toml: |-
    [discord.oi]
    AutoWebhooks=true
    EditSuffix=" (edited)"
    PreserveThreading=true
    RemoteNickFormat="{NICK}"
    Server="Oi"
    UseUserName=true

    [irc.alphachat]
    ColorNicks=true
    Nick="bridges"
    NickServNick="bridges"
    NoSendJoinPart=true
    RemoteNickFormat="<{NICK}> "
    RunCommands=["AWAY :I'm just a bot.", "PRIVMSG NickServ :REGAIN bridges"]
    Server="irc.alphachat.net:6697"
    SkipTLSVerify=false
    StripMarkdown=true
    UseSASL=true
    UseTLS=true

    [[gateway]]
    name="gateway1"
    enable=true

    [[gateway.inout]]
    account="irc.alphachat"
    channel="#oi"

    [[gateway.inout]]
    account="discord.oi"
    channel="ID:862302509699825675"
