---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matterbridge
  namespace: default
spec:
  selector:
    matchLabels:
      app: matterbridge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matterbridge
    spec:
      containers:
        - name: matterbridge
          # renovate: datasource=docker.io image=42wim/matterbridge:1.25.2
          image: 42wim/matterbridge:1.26.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/matterbridge/
              readOnly: true
          envFrom:
            - secretRef:
                name: matterbridge-secrets
      volumes:
        - name: config
          configMap:
            name: matterbridge-toml
