---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hastebin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: haste-server
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      STORAGE_DB: "${REDIS_DB_HASTE}"
      STORAGE_HOST: "redis-master.database"
      STORAGE_PASSWORD: "${REDIS_PASSWORD}"
      STORAGE_PORT: "6379"
      STORAGE_TYPE: "redis"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "content-paste"
          hajimari.io/appName: "Hastebin"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "paste.${SECRET_DOMAIN}"
            paths:
              - path: /
                patyType: Prefix
        tls:
          - secretName: "paste.${SECRET_DOMAIN}-tls"
            hosts:
              - "paste.${SECRET_DOMAIN}"
