---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.12.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    image:
      repository: bitnami/postgresql
      tag: 14.10.0-debian-11-r0
      debug: true
    auth:
      postgresPassword: ${MYSQL_ROOT_PASSWORD}
      createDatabase: false
    metrics:
      enabled: false
    primary:
      startupProbe:
        initialDelaySeconds: 180
        failureThreshold: 15
        periodSeconds: 20
      persistence:
        enabled: true
        storageClass: "nfs-client"
