apiVersion: v1
kind: Secret
metadata:
    name: discord-irc-config
    namespace: discord
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:WUV5EreliuTTqO5YyseAdc77UmC9GBRWxjHLbPV4q+sF4J7NGpF05AJNJ1zakMcgOwYwEuvJE3BP9aAZEX7q9DgaOTljxYqTJ+pZWS4yXD4BnAGOxPlmT+b7weTKZGp/FHf1oeYxwmmiEolosOvpbIHNB63sNMzfAl4sNeybfylFrr2XK0cdimsJBD1qVXMZIC8GB5rXetrjqd5LTQKe+qUw/4IXZL2gXBJVptFCX/uST5c26+GB/JA2ooMUeF3VjjPZFKO7OijIEx+89AKQYOvIhefpprr+sfa1VybP0f8yfauDb2Yur9GUnS3o/Dc2aj+u4EHJZeNCpl7mnG0TApR3JkgV4MzrAISodd1krc+N3yaKYzYuVqQA+AcDs2gzhLVwzZk9Miicn+bwoVRSNqJkkPbHzDNPwYktzMNMrVedxYQ5nLz3uv87f81X1j4Fkag0U3r/+v81ASX4lLnyxAMJFDietOSkTPe4Syx/qyED6F3G9c2S7OZVtpGhZ4KDioTD/MkHY5Q1NaupTt4f29/PCEc3B8iE7EJWMh/AyArDcVMBRnftcWvpXES1p3hpNQkUIpzGFT6U8uYnWt7WXz32L5/8wO39O1Jiq6DdREUpq3lK6ZF2mnjLNtiy3fXU7sdffEubuksRAyN2vZNETIzBx7U9CtVb3ITF7e4FYes7XOE8D9+ElDwLGfH+Y9Knn9BV3hCYdsqs1jXJ3hfnXJRAvUiRjk1N/AlRl0kvutZbRb56RhLEI4Z6NqbUn4qkkFlEbTdYU0/a4RoassXfRSyjMuitkywFWebdPbg0Fe3RRIfusKHAdv6aX5fup/9WhWaKyHOv33jVyKDAWtSYtLX8ERIWqsZmVUSmQMruREWIlLmAWQKSNy4J2PrI0eJGxZy35n3L/eNKpC0NQfrhhyhH7fm+ORh4mccLmzUAWSO18EOird+Vb1taICOFVJjUZ9SIiTwzsgjOOHo24zfi6fbfky41EefYaoqOAZDYJlBBvWxyzMYLrtst5WO8rGq3UZAadMNcznlsaeH9EmISNrHUvJPxxcZUaitH5m+gUNsq64HrxY1EjOmvBhHu4AQ6dOJw8UeTiLPcbgYn2wxq0smTP4zVH07zVA2HCgtQGlmK8Yi31OsYT6BIJop+MQZ5biJpoprioDi4g2LjEYhKg8jInjeiw/BV5SJLbbMh4iHfaFRJPOBZbeDLb/+mvIYLmAvu4B2DD/2hhKcoZ8S2r/k8+LBA7IGIfgVTvlm42/oQH/hKwuS1bgCz+XVutclIkQCzoPcBrb4kmCUUqd6rX34SYSbzusMLhdPut6P+/mn8o69o83ZMhAxCwF/a+y8jwQN/iIIjHt5PFVYREe2OgECk+9AnHFpyUs5cFDGM9g3WYDejFm4+yBCf+KcCHOLlHHbryoCTeHQMnZMziU0q8CaKLljByC2B01UKY9ApfRd+LVo79OxVKazLVVCmW52i2w+Sk5nUqzPlxpWqznzhb8JdLhnfBIhqOn4Jx4jV+VGgfZI1VWqqGRzp/Zh177vr5fZ5Ht35t5S3QpYTj/Mr1eE+s7OkZv4+GP4y7JaNweUlMsGCROeqnJZEIIm2sQkjEjjcaH8OjNF79hIWVkDamL1+fEpAFJSunvJPmWb59RRAzsdz/3EFGQV2JtNzdGObBOopPprr0kCdlVmWcb3eiEXdCHv8DgfMQKg2wUDBHTOyJJoWCa0mui+KxtrzT3vsFWnerN5CvBAAwhlNrFlpDa7S6KblgQAzq01D91Nc5BskJ8nMKjJvmGtPiMf+Oge0ZgeBp3qYLljBg/VhgIh6mDTqE8xbdzR5l8aTvZ0xHIaOY8tHqCLvSUyqfeYSXhz0hj/RZYvET2uIIGTHzUNVbZaFyNbWIHsmDJeYJdFkI322S0TOH1xxdKsif8KVik7Vmu6c3Guj7hgw6wFbNyaVw5x1/UKdZdybk+clr/o2AHmLC3uFSAb/CntlqSWBVDCTpJ2Urewl1HuXaNfBrp+/UxLMJhmk08Dn9+j1Bi8uwzBlrjG+hllyJcQdo7cQZrW8ULWloUN7f7GyjkNwMtIHw6nAtHFGwnBBKGy8GrzHG7s4/1YfjmIFAQ==,iv:kF/wFDSNOJyOaDQl1ZflX6qwhttY6NKJYRpODs0JOeA=,tag:3fIROEPB8QkSgSeGXJ9Ynw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeFN2aHg3MWpkSFR2OXZ2
            OFFxdm1VQVJUWnZRd0VJdHZDZ2ljNGkwNXp3CmdtUFdtMmZNazZ2T1RQSUlYQnJY
            bHVKbWxzZ3dmVUNycGNtR2JsZlhPT0EKLS0tIGZBMlhqWjcyRk9JY1VNaXdUVGRP
            Wm9NM2M4ZDBUcEc2MWczbXFXK3pqM1kKEw7yuxDk07pbCGjgX8d/7IjFxHMykFmK
            Jn0HyCQGwSFBWktXjb4wd1dfVc6gS4r3/ISeOlx/X8ClygL4dApUzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T16:23:30Z"
    mac: ENC[AES256_GCM,data:pCSAdYISEnjTD5wK5l6QKscL3AypimNQxYUP9EzGCNQyb5y1xRORv3VAiFqLQbVUsqCnlNYlXAV+2XSq6s+UolGuTuD33dgvZUFJ+j5RNthG4QTyv+jFfCnCcfR8w4EtY8qA5FDJI4vVskP/y1VE4dm3Lo+Q2n7+zmp6sI7FZvU=,iv:utdFQqAonO14qjqAzyh5HKJjhs/mTVmNA95AO+ZIkoY=,tag:TZ+gn3o7prL67JwanbNenw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
