apiVersion: v1
kind: Secret
metadata:
    name: discord-irc-config
    namespace: discord
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:8ArzJht20BIyz4MgAW1TtTPKEPKap8V3X0fnLfYdopb+urIT8ydfyhzVCY1A6C9tJ/pRc/z09K8Dn38VweB0TPObE8mL6PA2a0PkRHGgMAxXqhnYb3M6+8h2mhwxMyvyyd+hhwe+LyFW103z4JcN9VaFAhTYqMrXecFCXDDk3k0gR7sAbwP2q2hbyy7aAlxM0tJhXGaJbRYZ8JhLRMc4YOLgpn75Ix0Cquaf4/AfAPvcyh3aFG5B9Dl9UwAFMb49SJAVd11jxdQ2JSq9i6ifGIOUi7ekZFMTstBNVM5DVfWGgM7XgKzoXNFApXufQFHbEsUp/1qbciRvDUjKoK/jJQBnnKM1pHCxxHjH/DaSdcMXhP4USbqIVBdsPBPQmV3paTaDqXg4Lceu54RgSPWw0JplugABu/vDh+BlteWEqqJxPVKYR/m3bFecqX2e2JW64KJPeB7tiE/z+RxXLeYaDqgKhh1JuKx5KEakELH0fU2LGsrAJZaDMvnynNucjEIPxJ2vg4Phdk3SitRelj9D74krB7syBi3vmG9XjfwiPPC2jikOWwryXdCUFR4dEoHkEruf+sPycmk44lWujEfZP7Nfl4y8WArrR58XUyFQvuzSio33HVHbT0gs++jtP+V5uUac+bxZHrnsujXn0qOuYHGuqr/soDcKYtQJ3fWJGn/3KXKVXCZ4dj/7fYT4QsdkqvraPWXt5TTkEsEG2RzPul60iB0RCGCZKomPc7tUhicbiQDxeUcF1M7W29VbbNu7UYNvBjo10tag4zqHGsVOmsglJrs1UxwR8/nkaXSQjjg95/6tKE/ah6mLkp2O2rR2XLMIs5H/D1HTeRF98G2uE5w59O5uYzrvGDf3lBeIOHwApevc0balPUvTy5Cfpmvj/jQA5rWa4ogqIvsi3cLEgXZTDlE2r4qjiXjIP0T+HFr5Rqi25UAZ1OEPlbjmSEjvEfQLfKFjqMgdnaEVsaDS13tFfU3U43LE+oq8KIAi4ifsvPGJERgSbBR2YfWtRr85DwYxFZu0z/V8n4z0h6Z2bKoZ0LOU2Nu5n4S4Of5f+/DiD4eveb2vN7H7QjIDw19YM+F6k7fHcXQ49+K+f4ajsBgT+kUlijwlrLvW1PwVO2WYM7cJEKCN9dbCcT6LeAs79KgGlfIlMARqnE8fQpcMqYlcl10bhyJxsEoGZCFkdKSBCA+qB4nzRAk5Ngddd/INlz/EfZQYf8c5X0NQK3PeuQBZwq0Hvc2U0Wq5wr+lH6QmY1v7GxekpMlR8/nLtOXbBWrinjHM1kNajSISs3zyGWYdy0uNDaL2j/xKtH7qarVeGennCE+eRZrOeHBtBGttEuVoFu4F1360BrnaV+8YvFUia/vH1E/sZtacz/ge9d+3xSe96C0h4me2Vy5jdzTM8ouXXE4il59oJYo2MT8CoXuk/PHL2OoNSiMU2IwiyYcimr/iVcCHVNstxdwXW7C5JmENra5pCTOAaWD0YdIyEBw8n8q7/5nDThe62yxUacC91YaaQrEpPFKVJDC9j3n8SOrKlWOQhJt9d9Exjmq3wuHI0X9urz7NvdMf02qcN20jiFlt0doLiql5qfEsz/xBmGN9Se8zWyayyLFvZdpYc0QhF1fGi27eDevRWRNF0tnSsr0qhzFUhHm1jbYe2uwlmTI7/yOxas6fVyKQ6370aTAOXlkJYtUMxW2rOczRReLqQz0MjZtwwzoBZQ1TR5MbQQXulbvRaDeqmIEo1ivgcnyWZGXyccOAHfwjDskIrhYvT1KsjN5ulqjILdrwneRgltgcUvXQeT3nYIS4wczgU2SrEnUSOjSeAlOOiujMgRI2oOlGgB+QqW/E32ksgC9O3p8Mlf9B5aGsriFW3iZ3DwdrcIRi3i7Szz9S6O9C53HJC7opL5Sz3oft1tZQT7xESLttXhS/qL7e8kGIAwka8aUEqhFqKl02Ew7k7QDPWJpJ+vJjKjwYOgZGoIOj1P92NeWD/YUd4ZiqPXWMDeOO6h3PDOPgC7UTrfbaZVjrHrAo66nqBJEL9B5qtOALmd+LYsfstIda0CcyEIVoGSY+qBS9N31OQ0gSgrwVZ1pWgcfva5Qt52bjjbLqr4nVIF2A4/hstL0CzFV0UnZFLN59F+a5HPtWP9pU9mo1/L7w1uK9yFVw5kdWx5fItxK8io7/NNUvHzXRkCc=,iv:a9L68IpYusq/EtvVAAHoFQTMpTIkthUjSz/8lPgYqY0=,tag:6ToUqd4XJGlkBmpsV+qglw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeFN2aHg3MWpkSFR2OXZ2
            OFFxdm1VQVJUWnZRd0VJdHZDZ2ljNGkwNXp3CmdtUFdtMmZNazZ2T1RQSUlYQnJY
            bHVKbWxzZ3dmVUNycGNtR2JsZlhPT0EKLS0tIGZBMlhqWjcyRk9JY1VNaXdUVGRP
            Wm9NM2M4ZDBUcEc2MWczbXFXK3pqM1kKEw7yuxDk07pbCGjgX8d/7IjFxHMykFmK
            Jn0HyCQGwSFBWktXjb4wd1dfVc6gS4r3/ISeOlx/X8ClygL4dApUzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T16:05:08Z"
    mac: ENC[AES256_GCM,data:GBfLYtukYw0xr6dxfSsyawuZuRxfgLUHZxhvhAuXPj69z4J21MtvcKKAif73kbwrmpXZBMpKzm7KNUc6sllD9+SQHtrreG6kT0KS69wfa/mAMMy91mTPPSz6CjUkW4uYngzfih/poOErhZtCygiqoX9dQ9m5HExGgvguQn4VrAg=,iv:2HAjXeJopxGb33oF6D/qJRI4hvUyofToplLFfndhl8I=,tag:JLI76ZGp3RH9cTLrc8QkOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
