apiVersion: v1
kind: Secret
metadata:
    name: discord-irc-config
    namespace: discord
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:2xbhrSvTnh0BvkIgWNGy/2eOPPK7G9+Gyw1ZXgZm15ylSq9qiIWgTBTYtNI+QLqWtlTJwoVg4Xu2f3aVE+vkXLWYSGGuAsd2Ns2sMbvk7uNqBvAi3c0ddxprnloOx2kikfokaQuNbobRK/TqKuOy638tQsdyvfSLypVyWaprfvBC0YdSEyJiDO75cEJKpKC7NebXdvXazEIsdxio9m9pmUzc+6g33qzpEhnntYDtoSb6oiCl4RqdX9PWkRswnFpRb6hverv0EFkSwflQaoTAiCImiqN+uSB+NoDr19KVcupzzSDXM5uNqN9R92r4+BeR/qN9VqkOzezkOkffVZgxamj1fNIUpYkO/0YV+VbtnT3HtD2UHA26SpSoSgHrM7SW9Rda9csHpVzsjC6ebGB2MYG9KKKzVQTf2klxvOo9RhV9IHYP9gBQTOO56qFqQl3M/nUTrZnWqtbmUtJMlSpIEIAq1/g3h/j52SoDkdo+KGs5fwAuYNJCt8WBgMLHUQX9Oz2y+K64f6a82c4Pulakqf8fsypKF8EvBFJMHtCsbVF3BZEMUoLHJV2JnfDZthvVsjoKYXhA0wIOZi/I3Bkfnfo85WGwl1RaooTHl/5xbd9NkaETBFywK9KgNwFfH8odR55jr9wF7TweCwef0uZVakz0koXPavjjwfKL20EUJbLQthTTeG/WZlsO2n58pDTV5LMFvG9om3CBNNl7je0cdZW8mYwOJ47xkWoOhAgvZb/Sf8ZhqJYLAMYfOOyE+BdUi3UiLo4yWEZgg36ZBazPtrtT9VPG4fLYdwHA/9Z2MfyHgy9E7ZdHCNjAovoz1pClZW7k+ekiNKbNsSA2eVlEdCvkFQqoeyOMIhRY6J/1Jn/3EVgo9UeMkrSZxVLvSEzeuEJCffNjwsA+xUtcqbl0huYAdUT91R/dIDxrRihThu+ywjnL8Kx1jpu+pTll4egUKJCxamVnizvi2g69xKPjSrBMaEstes7BaR30T9dWPaQFgD/wTNHp92RYfwI0F/FH2R8umRt5XXyAEC2ZUTIyruRj/sPSzpXfbn5aL6Fb7kBZb5PBW2GS/ZY3WmIlp+olrv/uwTltx3O/oSKWItBSlm/B1aQY9D4s0+P98U9BfmpdobUhX4ZX79eypHCU2R+R9ZRMrJMXwJaIzADr9cOJnFxNPg0uN9YTy89e6DU8+aWxqhY6qesaDQ5eUPST2r5RTEvzK3LAvjQHtVRgFSvII1oGd1+u9MFzMEbx7Quzm8UX/BPwCBHm44KEBnLwIaNPiDrUIfNtQonLu3ncQSq28dhtwvfOGyKfoK+Un1sxuERD6M6jOuSwBC7nyEctB1iZ+GBWde2difFFQvKDcN74tFAJE0tD6YSsJuA6oz83nSy4kdbbO4e31E3rRkEgX62IDp5hj2wvyXudolgHMkzTrmS49e0UvF3UTFPEYRvieXprDA2Bvv8hkm80dtx2aBm0LASg1GZsq2kfC+WRJ0bXhUJHGzR+smiNyzduCFEkZmeC0ZTblTZBkO/rISh3uzbVtO3KQBBE8wPAo/YgfbAWXRlhvb+92TFbW4EONDEQG3W0I3L2ZYdUvXoneXgoCL3tN7qznfdskDzglJGauVkFD1Q1DEZJ7it/ScGagYZHgc7F+KJHK/zN9HHuS/qO2R0R6ueuhELD9HyLC0sD8q1yB4ZfgNvMly16tdPsCxR8G6Zobppkc3Ba/Sjk07vIRao6jEFRIEhKQrZxk1KokqlKbMdwPubXzm0NlkAuP0wimqtBIbZlZn5ZjNmv1s4byIDmTiNjuj3baxTofqgoH7LhdxYfA4OrqsmGTlEs/MEt9K7O5Vpf+uyIU+ZPTqsNsvxWBhd0jRFySNdRf/hATkQwhanmE38ucyPXRqiIxued7wAJS8/1biKhMQga6cvFkuon/MJQAk+e4BvsOQHWRObue0qxinLI/K7FIhCAO0V9cD3+A08S8/xpGzYS1EhN/M9Tv74xmMnIgrh7qxarkguXgPKIgyFEafLs2j48kkSF9YG6VvFn0zO5EqoxqJ63rxsW6C9mZAByNX0UrSlENz3bzXCobPPVzjAJycYzN+SxdyHEejSOt6qCm8NYImFMSgpmTkENdcQQW5TBj/HcPcZXupCKs8njdoOmz57IPQ==,iv:ObM0Ifn5Ea9fgeVLTQSJujKPYzA+0lkvdq8HlN9eTjs=,tag:CteUCV4/1DFVkcTXXfT2HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeFN2aHg3MWpkSFR2OXZ2
            OFFxdm1VQVJUWnZRd0VJdHZDZ2ljNGkwNXp3CmdtUFdtMmZNazZ2T1RQSUlYQnJY
            bHVKbWxzZ3dmVUNycGNtR2JsZlhPT0EKLS0tIGZBMlhqWjcyRk9JY1VNaXdUVGRP
            Wm9NM2M4ZDBUcEc2MWczbXFXK3pqM1kKEw7yuxDk07pbCGjgX8d/7IjFxHMykFmK
            Jn0HyCQGwSFBWktXjb4wd1dfVc6gS4r3/ISeOlx/X8ClygL4dApUzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T15:50:21Z"
    mac: ENC[AES256_GCM,data:4WXdsG4PFt50WAirwHRFi5dCgiHX36olsK8SwGGre9xvRY0ZLzIWRe8N3eM8m19fuG9Ugz+iZPicjUeDws3CL038dneOaj6Qelw8C3pwuiEtllyyQL7hdypEkmUsYUWsudTS0f/nL0VAshtqSPWTkDZzmLW98wtsXOUbfSii91s=,iv:hsIieF4kxKoYUi4tfR+nO+UEgC+mMS863z3HFFzt7fg=,tag:dqCrT3CUpqRRuHbNSeatvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
