---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-irc
  namespace: discord
spec:
  selector:
    matchLabels:
      app: discord-irc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discord-irc
    spec:
      volumes:
        - name: config
          secret:
            secretName: discord-irc-config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: discord-irc
          image: discordirc/discord-irc:latest
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
