# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:a4VxJHJ1snIjzrUm,iv:wuDPwiLI698DSaWaFhU+lqSCOh8BLN72SwPPMIHgOyk=,tag:Xs7A7WUs1sJ3ac/icxVnLg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qW4QXNKqYdm2/P4zMxeR2Q4ctfvZp6JI,iv:A+QVB63AQYMNdDJ3J+bJHTA80DmPzWpUSSc1DribEiQ=,tag:XL36LdFX7mfd3vc5zGmpPg==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:Kg1rB1K+MLoEHgSudw==,iv:ukn4KDioELDpXcvep4xK2MwZEQCwhe3iGAytgA/ZS9U=,tag:87ScPreuEjQE2GcyyF351Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUHBJZGQ2cGFEakplZXl1
            cENTN09hTlBLWWVVWnpBNnhlOE1LN3YwVmdBClBZbGVHc0xEd2ZJQVMrUFRGMzhv
            RzhSZ3I4RVBRSUVrRzZxNWpKRUFVSUEKLS0tIE1LZTV3KzNvOFdWN0hGditHWDk1
            ZXYzYUVvNnpNZDFadFUxS2xhRksyQjQKggkz/Wly7CgdqncqBk6qD5yCNRnmzY5y
            YIvGI0B50FKHF+yrb1c1UCQ5Ai1GJLFM4FNv0RQpK/KefazTuY1Uhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T20:06:46Z"
    mac: ENC[AES256_GCM,data:oBXbDqCfipcKTIWje0JiZcHZDCXI+kkQMR16PFosk+mIzt3mevIyHlB22lre3coUoNmCbpcPpjRhpmDNFR4Fhny6jibpRjpojM/yDICuCS3MQX1JkSwYeLW9z9Sxzt0/uTRu0xknos7fO9+Fhp7jjg+pAX6qZP7Q24VjOjZOisM=,iv:MEuvhRqJ9vBiHm0FdiyV1XgveeGZkBB3HM1/9X3ns1E=,tag:JEwrEoPjGJ3FDVtwleA+GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
