---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Kentucky/Louisville
  METALLB_LB_RANGE: 192.168.86.10-192.168.86.20
  METALLB_K8S_GATEWAY_ADDR: 192.168.86.10
  METALLB_TRAEFIK_ADDR: 192.168.86.11
