---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    service:
      main:
        enabled: true
      dns-tcp:
        enabled: true
      dns-udp:
        enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "blocky.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "blocky.${SECRET_DOMAIN}"
    config: |
      upstream:
        - 1.1.1.1
        - 1.0.0.1
        - tcp-tls:dot1dot1dot1.cloudflare-dns.com:853
        - tcp-tls:one.one.one.one:853
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        clientGroupsBlock:
          default:
            - ads
