---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 16.13.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    auth:
      password: ${REDIS_PASSWORD}
    master:
      persistence:
        existingClaim: redis
    replica:
      persistence:
        storageClass: "nfs-client"
    metrics:
      enabled: true
