---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: database
spec:
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
