---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  values:
    memcached:
      enabled: true
    persistence:
      storageClass: "nfs-client"
    postgresql:
      enabled: false
    gitea:
      admin:
        existingSecret: gitea-admin
      config:
        APP_NAME: "Gitea: With a cup of tea."
        service:
          DISABLE_REGISTRATION: true
        server:
          DOMAIN: "git.${SECRET_DOMAIN}"
      additionalConfigSources:
        - secret:
            secretName: gitea-config
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        hajimari.io/icon: "git"
        hajimari.io/enable: "true"
        hajimari.io/appName: "Gitea"
        traefik.ingress.kubernetes.io/router.entrypoints: "web"
      hosts:
        - host: "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
    serivce:
      ssh:
        loadBalancerIP: ${METALLB_GITEA_SSH_ADDR}
