---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 5.0.9
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  values:
    memcached:
      enabled: true
    persistence:
      storageClass: "nfs-client"
    gitea:
      admin:
        existingSecret: gitea-admin
      config:
        APP_NAME: "Gitea: With a cup of tea."
        service:
          DISABLE_REGISTRATION: true
      additionalConfigSources:
        - secret:
            secretName: gitea-admin
    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: "git.${SECRET_DOMAIN}"
          paths:
            path: /
            pathType: Prefix
    serivce:
      ssh:
        annotations:
          loadBalancerIP: ${METALLB_GITEA_SSH_ADDR}
