---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app plex
  namespace: media
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
        - name: gdrive
          hostPath:
            path: /var/lib/rclone
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: rclone-cache
          persistentVolumeClaim:
            claimName: rclone-cache
      containers:
        - name: *app
          image: plexinc/pms-docker:1.29.2.6364-6d72b0cf6
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: gdrive
              mountPath: /gdrive
              mountPropagation: Bidirectional
            - name: plex-config
              mountPath: /config
            - name: rclone-cache
              mountPath: /rclone
        - name: rclone
          image: rclone/rclone:1.60
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          args:
            [
              "mount",
              "-vv",
              "--allow-other",
              "--allow-non-empty",
              "--umask",
              "000",
              "--dir-cache-time",
              "96h",
              "--vfs-cache-max-size",
              "500G",
              "--vfs-read-chunk-size",
              "64M",
              "--vfs-read-chunk-size-limit",
              "1G",
              "--vfs-read-ahead",
              "2G",
              "--vfs-cache-poll-interval",
              "5m",
              "--vfs-cache-mode",
              "full",
              "--drive-pacer-min-sleep",
              "10ms",
              "--drive-pacer-burst",
              "200",
              "--vfs-cache-max-age",
              "5000h",
              "--cache-dir",
              "/data/cache",
              "--bwlimit-file",
              "32M",
              "--poll-interval",
              "10s",
              "--config",
              "/data/config/rclone.conf",
              "gcrypt:",
              "/gdrive",
            ]
          lifecycle:
            preStop:
              exec:
                command:
                  ["/bin/sh", "-c", "fusermount -uz /gdrive"]
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: gdrive
              mountPath: /gdrive
              mountPropagation: Bidirectional
            - name: rclone-cache
              mountPath: /data
