---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - port: 32400
      name: http
      targetPort: 32400
    - port: 3005
      name: local
      targetPort: 3005
    - port: 8324
      name: roku
      targetPort: 8324
    - port: 32469
      name: dlna-tcp
      targetPort: 32469
    - port: 1900
      name: dlna-udp
      targetPort: 1900
      protocol: UDP
    - port: 32410
      name: gdm1
      targetPort: 32410
      protocol: UDP
    - port: 32412
      name: gdm2
      targetPort: 32412
      protocol: UDP
    - port: 32413
      name: gdm3
      targetPort: 32413
      protocol: UDP
    - port: 32414
      name: gdm4
      targetPort: 32414
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: ${METALLB_PLEX_ADDR}
