---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400
    - port: 3005
      targetPort: 3005
    - port: 8324
      targetPort: 8324
    - port: 32469
      targetPort: 32469
    - port: 1900
      targetPort: 1900
      protocol: UDP
    - port: 32410
      targetPort: 32410
      protocol: UDP
    - port: 32412
      targetPort: 32412
      protocol: UDP
    - port: 32413
      targetPort: 32413
      protocol: UDP
    - port: 32414
      targetPort: 32414
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: ${METALLB_PLEX_ADDR}
