---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - kube-system
  - metallb-system
  - mysql
  - namespaces
  - nfs-subdir-external-provisioner
  - redis
