apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    password: ENC[AES256_GCM,data:JgYdlz3zU2Mf8GyatLgeMf6+pVD6Xd1lTAJ++EGyT0rjK2DRmzpzdSg7L9CqNGn19tHRYFnKXCHCYnwvv0CtXK5Hu11DompQuJz2+0lfPNd5jy8JP/FbcV+rA6P27a7DdLloc3NG9MDWeIHAxqAY9GODjly6V4VPgrFsA6ALg7A=,iv:9CdYd2YKHfk2lBxhdgFlUHXv+OIzyafm/iUN6BUDHmw=,tag:FrIw8D2Ui6G/HQuuzRQH4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMnZHNkxsajdkR2ptSk9x
            cXBaYW9rNVNJS1g3Zk1aQ3RFV2gyOTNkY2tVCkVMaEp6NU1ZeUkwbW9yaVBFVFpw
            OXA2a2xUS3U3U2hBanVKenRyNGVvWkUKLS0tIGkxUitadlNjZllOVitlWWlKVWhX
            UWUydlg1V2lZWWRFYStHSm9IT0M0UEkK/z8iAQBLqmeaxYgc6fFSvmwVogcXWmb8
            DaJUClf+MehgVsHpWWcJnV844PZpO2ldzl9AmYoTA/tsNse04Y9SpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T23:33:00Z"
    mac: ENC[AES256_GCM,data:Se1Re6uhotgtckQrW8GLHgVwjVOCLMVcPHTyhZoMxswWkMf7996Fr2bYftoH3gXXl4u+/jrOfZ0YcU8O8noNMRIo1/c41ocomZgFTGPD2G5eroIi36ThkcvDySD0Yj/xk+UpoacwfuZBs3O3dqiYPBJ6CGOnjollQXzHmOcl9Ac=,iv:xLhYr9r5RiLJsY9UmEHNs+IxH6IjS+MAYl5HmyRiKxo=,tag:PVPwmN6TD5VkUhKNwxsx1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
