---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: 9.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    image:
      debug: true
    auth:
      rootPassword: ${MYSQL_ROOT_PASSWORD}
      createDatabase: false
    metrics:
      enabled: true
    primary:
      startupProbe:
        initialDelaySeconds: 180
        failureThreshold: 15
        periodSeconds: 20
      persistence:
        enabled: true
        storageClass: "nfs-client"
