---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - discord-irc
  - flux-system
  - game-servers
  - kube-system
  - monitoring
  - networking
  - system-upgrade
