apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:QCnmO8L3yG00gH0TD5VPNrbrKlu1MX9neaXpwkGwzwZ8UxHMAzaLQ3eibymqKMN9ca7CORYttJQ=,iv:CIDBFnC4jAn67wnEf27zy0+iBXh/iyXN9pmoVJpLVSg=,tag:g890tBLVpw7V5mlBqIGMzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1el003vswpd947mtzcvdmtawkk0vnupmzdcfaa3e3ctwznqnjaqlqq3auhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY3pZcVFzellBL3RhVFdU
            OFpiK0FTSVJGbDlPTkFkNDVCTzE5U3NuTkhjClNOc09LUVNUYTFKaTJKdHpTSG5o
            WnlEUG5ZNVNOall6c2JiYVNLZ0NsR0kKLS0tIGNub2lLdkpibmQ1K2l0KzJNcERN
            U0E0T0ZGbUlRU083WE5Zb25SdTVNTDAKiwm/kyGYlDMCX34fv1Wx76fyEh2c0L3r
            gTWXhH9tPnCcZekqaGtZu5xJepX8ltLpJPjbyTJtzAgYJCxDS2ka/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T20:45:17Z"
    mac: ENC[AES256_GCM,data:Ia2g/FJeX6Zb3OGNhAWum0QzxGvBrcXoqx2lZnCx1w+IqVbRG3JrhDedsY38IPsUpF5WF873v5B21DXO28Fm7kV//oQOHiPCWJiBEbcRm2EHncRDr4uQjrikDI/kA/A6oVayJjZE2/5+n/Goqj4+BHbbtQ8yBJ7rRp3SUo0QJeQ=,iv:QfFMHGJlmBXqy7eALULWw8pwOuvb2c9/cXczryloHLg=,tag:Dd0rsLMJqjqZcAdxdo0kyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
