---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: syncthing
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.20.4
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "autorenew"
          hajimari.io/appName: "Syncthing"
        hosts:
          - host: "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: /var/syncthing
