---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - database.yaml
  - game-servers.yaml
  - kubernetes-dashboard.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - system-upgrade.yaml
  - storage.yaml
